### PR TITLE
Fix #81 - Current editor language does not change on save

### LINKED ISSUE #81: Current editor language does not change on save
The language attribute of the current editor should change upon a successful save of a file if that file happens to be of a supported language.

### PR DESCRIPTION
**Pull request by PoLaKoSz**

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
I forgot to update the `changes.xml` file but before i commit here i wanted to make sure this is the right format:

```xml
<action dev="Tom PoLáKoSz" issue="ISSUE-0081" date="08-21-2019" type="fix">Current editor language does not change on save.</action>
```

I updated the title of this PR to match with the issue which is fixed by this, but i have doubts about the date value.

**Comment by Hexman768** [comment]
That is the correct format, thank you so much! I'll test this PR and get this merged!

**Comment by Hexman768** [comment]
Alright, I just tested this PR and the code change seems to fix the issue, just waiting on you to update the branch, I will merge it as soon as I see its updated! Thank you so much for your contributions to the project!

**Comment by PoLaKoSz** [comment]
Thank You so-so-so much! I want to say that i can't describe how happy i am because i was never a contributor like now to this repository. :smile:

**Comment by Hexman768** [comment]
No problem at all, I've been in need of some help with this project recently as school has started back up and I am very busy with work and school, I am only able to work on things on the weekends if that anymore.

**Pull request merged**
